name: mypage

services:
  start-dev:
    container_name: start-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    ports:
      - ${APP_PORT:-3000}:3000
    volumes:
      - ./:/var/www/html
      - /var/www/html/.nuxt
      - /var/www/html/node_modules
  start-prod:
    container_name: start-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - ${APP_PORT:-3000}:3000
  npm:
    container_name: npm
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    user: ${UID:-1000}:${GID:-1000}
    entrypoint: ["npm"]
    volumes:
      - ./:/var/www/html
